spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: http://localhost:9090/
          predicates:
            - Path=/customers/**,/customer/**

        - id: accounts
          uri: http://localhost:9091/
          predicates:
            - Path=/accounts/**,/account/**
